### ISSUE TITLE
Fix error 500 from play endpoint when parameters not provided

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#83] opened 2020-05-02 01:03 UTC
Observed behaviour:
```
$ curl <BASE PATH>/v1/games/1a42709f-a9db-4db9-84d8-b1de693a2799
{"admin_nickname":"Slippery_Sloth","public":false,"status":"Running","round_number":1,"max_cards":11,"players":[{"nickname":"Slippery_Sloth","n_cards":1},{"nickname":"Slippery","n_cards":1}],"hands":[],"cp_nickname":"Slippery","history":[{"player":"Slippery_Sloth","action_id":10}]} 
$ curl <BASE PATH>/v1/games/1a42709f-a9db-4db9-84d8-b1de693a2799/play
{"error":"500 - Internal server error"}

**Comment by maciej-pomykala** [comment] 2020-05-03 14:38
I could not reproduce it locally. I will seek a way to debug it using a version running on the EC2 instance.

**Comment by adrian-golian** [comment] 2020-05-03 14:48
The error still occurs, with the current deployment.

**Comment by adrian-golian** [comment] 2020-05-12 20:37
Can't reproduce in `v2` either. Assuming it's fixed.

**Comment by maciej-pomykala** [comment] 2020-05-13 20:40
In that case I should close it

**Closed by maciej-pomykala** 2020-05-13 20:40 UTC
Labels: bug
